### ISSUE TITLE
Permission Denied error

### ISSUE THREAD

**Issue by arihid** [knrdl/hubleys-dashboard#217]
Hi! This project looks awesome, and I want to try it out.
But I always stuck on `Error: EACCES: permission denied, mkdir 'every directory'`.

Things I've tried:
- Run as root.
- Detached volume binding.
- Running it on three different systems.
- Running both edge and latest.
- Defined PUID=1026 (my current user) and PGID=101 (administrative group) on Synology Container Manager.
- I can't connect to the container since it was always abruptly closed after permission got denied.

Test systems I've tried:
- Synology Container Manager 20.10.23-1437 running on DVA3221.
- Docker Desktop 4.26.1 (131620) running on Windows 10.
- Docker 20.10.21 running on Ubuntu 22.01.2 LTS VM.

I'm attaching the error log error.
```  path: '/data/logos'
}
Node.js v21.5.0
node:internal/fs/promises:855
  return await PromisePrototypeThen(
         ^
Error: EACCES: permission denied, mkdir '/data/logos'
    at async Object.mkdir (node:internal/fs/promises:855:10)
    at async Promise.all (index 0)
    at async onServerStartup (file:///app/server/chunks/hooks.server-0W6GFEIO.js:67:3)
    at async file:///app/server/chunks/hooks.server-0W6GFEIO.js:81:1 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/logos'
}
Node.js v21.5.0
node:internal/fs/promises:855
  return await PromisePrototypeThen(
         ^
Error: EACCES: permission denied, mkdir '/data/logos'
    at async Object.mkdir (node:internal/fs/promises:855:10)
    at async Promise.all (index 0)
    at async onServerStartup (file:///app/server/chunks/hooks.server-0W6GFEIO.js:67:3)
    at async file:///app/server/chunks/hooks.server-0W6GFEIO.js:81:1 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/logos'
}
Node.js v21.5.0
node:internal/fs/promises:855
  return await PromisePrototypeThen(
         ^
Error: EACCES: permission denied, mkdir '/data/logos'
    at async Object.mkdir (node:internal/fs/promises:855:10)
    at async Promise.all (index 0)
    at async onServerStartup (file:///app/server/chunks/hooks.server-0W6GFEIO.js:67:3)
    at async file:///app/server/chunks/hooks.server-0W6GFEIO.js:81:1 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/logos'
}
Node.js v21.5.0
node:internal/fs/promises:855
  return await PromisePrototypeThen(
         ^
Error: EACCES: permission denied, mkdir '/data/logos'
    at async Object.mkdir (node:internal/fs/promises:855:10)
    at async Promise.all (index 0)
    at async onServerStartup (file:///app/server/chunks/hooks.server-0W6GFEIO.js:67:3)
    at async file:///app/server/chunks/hooks.server-0W6GFEIO.js:81:1 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/logos'
}
Node.js v21.5.0
node:internal/fs/promises:855
  return await PromisePrototypeThen(
         ^
Error: EACCES: permission denied, mkdir '/data/logos'
    at async Object.mkdir (node:internal/fs/promises:855:10)
    at async Promise.all (index 0)
    at async onServerStartup (file:///app/server/chunks/hooks.server-0W6GFEIO.js:67:3)
    at async file:///app/server/chunks/hooks.server-0W6GFEIO.js:81:1 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/logos'
}
Node.js v21.5.0
node:internal/fs/promises:855
  return await PromisePrototypeThen(
         ^
Error: EACCES: permission denied, mkdir '/data/logos'
    at async Object.mkdir (node:internal/fs/promises:855:10)
    at async Promise.all (index 0)
    at async onServerStartup (file:///app/server/chunks/hooks.server-0W6GFEIO.js:67:3)
    at async file:///app/server/chunks/hooks.server-0W6GFEIO.js:81:1 {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/data/logos'
}
Node.js v21.5.0

**Comment by knrdl** [comment]
hi there, i'm sorry to hear that. 

I've updated the edge tag (`ghcr.io/knrdl/hubleys-dashboard:edge`). so when the `/data` folder is not mounted as a volume (demo mode), it should work again.

The node process in the container runs as **PUID=1000**. So the volume must have user **or** group permission set accordingly, e.g. `sudo chown -R 1000:1000 ./data`.

> I can't connect to the container since it was always abruptly closed after permission got denied.

Part of the init procedure is to write to `/data`. As this fails, the container keeps crashing

**Comment by arihid** [comment]
Thanks, it's working now.
